name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker buildx build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/tydom2mqtt --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tydom2mqtt
